[package]
name = "backend"
version = "1.0.0"
authors = ["Diamond <33725716+DiamondMiner88@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.7"
tokio = { version = "1.3", features = ["full"] }
tokio-postgres = "0.7.0"
#futures = { version = "0.3.13", features = ["compat"] }
futures = { version = "0.3.13" }
futures-macro = "0.3.13"
warp = "0.3"
juniper = "0.15.3"
reqwest = { version = "0.11.2" }
async-tungstenite = "0.13.0"
log = "0.4.14"
